name: 3dep
channels:
  - conda-forge
  - defaults
dependencies:
  - appnope=0.1.3=pyhd8ed1ab_0
  - argon2-cffi=21.3.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=21.2.0=py310h1961e1f_2
  - asttokens=2.0.5=pyhd8ed1ab_0
  - attrs=21.4.0=pyhd8ed1ab_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - beautifulsoup4=4.11.1=pyha770c72_0
  - bleach=5.0.1=pyhd8ed1ab_0
  - blosc=1.21.1=h97e831e_3
  - boost-cpp=1.74.0=h8b082ac_8
  - branca=0.5.0=pyhd8ed1ab_0
  - brotli=1.0.9=h5eb16cf_7
  - brotli-bin=1.0.9=h5eb16cf_7
  - brotlipy=0.7.0=py310h1961e1f_1004
  - bzip2=1.0.8=h0d85af4_4
  - c-ares=1.18.1=h0d85af4_0
  - ca-certificates=2022.6.15=h033912b_0
  - cairo=1.16.0=h1680b09_1011
  - certifi=2022.6.15=py310h2ec42d9_0
  - cffi=1.15.0=py310hcc37b68_0
  - cfitsio=4.1.0=h2c97ad1_0
  - charset-normalizer=2.0.12=pyhd8ed1ab_0
  - click=8.1.3=py310h2ec42d9_0
  - click-plugins=1.1.1=py_0
  - cligj=0.7.2=pyhd8ed1ab_1
  - cryptography=37.0.2=py310h52c3658_0
  - curl=7.83.1=h372c54d_0
  - cycler=0.11.0=pyhd8ed1ab_0
  - debugpy=1.6.0=py310h9d931ec_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - draco=1.5.2=hbb4e6a2_0
  - eigen=3.4.0=h940c156_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - executing=0.8.3=pyhd8ed1ab_0
  - expat=2.4.8=h96cf925_0
  - fiona=1.8.21=py310h5a20164_2
  - flit-core=3.7.1=pyhd8ed1ab_0
  - folium=0.12.1.post1=pyhd8ed1ab_1
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=hab24e00_0
  - fontconfig=2.14.0=h676cef8_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.33.3=py310h6c45266_0
  - freetype=2.10.4=h4cff582_1
  - freexl=1.0.6=h0d85af4_0
  - geopandas=0.11.0=pyhd8ed1ab_0
  - geopandas-base=0.11.0=pyha770c72_0
  - geos=3.10.3=hb486fe8_0
  - geotiff=1.7.1=ha1a2aeb_2
  - gettext=0.19.8.1=hd1a6beb_1008
  - giflib=5.2.1=hbcb3906_2
  - hdf4=4.2.15=hefd3b78_3
  - hdf5=1.12.1=nompi_ha60fbc9_104
  - icu=70.1=h96cf925_0
  - idna=3.3=pyhd8ed1ab_0
  - importlib-metadata=4.11.4=py310h2ec42d9_0
  - importlib_resources=5.8.0=pyhd8ed1ab_0
  - ipykernel=6.15.0=pyh736e0ef_0
  - ipyleaflet=0.16.0=pyhd8ed1ab_4
  - ipython=8.4.0=py310h2ec42d9_0
  - ipython_genutils=0.2.0=py_1
  - ipywidgets=7.7.1=pyhd8ed1ab_0
  - jedi=0.18.1=py310h2ec42d9_1
  - jinja2=3.1.2=pyhd8ed1ab_1
  - joblib=1.1.0=pyhd8ed1ab_0
  - jpeg=9e=h5eb16cf_1
  - json-c=0.16=h01d06f9_0
  - jsonschema=4.6.0=pyhd8ed1ab_0
  - jupyter_client=7.3.4=pyhd8ed1ab_0
  - jupyter_core=4.10.0=py310h2ec42d9_0
  - jupyterlab_pygments=0.2.2=pyhd8ed1ab_0
  - jupyterlab_widgets=1.1.1=pyhd8ed1ab_0
  - kealib=1.4.15=h4dab1bc_0
  - kiwisolver=1.4.3=py310habb735a_0
  - krb5=1.19.3=hb49756b_0
  - lcms2=2.12=h577c468_0
  - lerc=3.0=he49afe7_0
  - libblas=3.9.0=15_osx64_openblas
  - libbrotlicommon=1.0.9=h5eb16cf_7
  - libbrotlidec=1.0.9=h5eb16cf_7
  - libbrotlienc=1.0.9=h5eb16cf_7
  - libcblas=3.9.0=15_osx64_openblas
  - libcurl=7.83.1=h372c54d_0
  - libcxx=14.0.6=hce7ea42_0
  - libdap4=3.20.6=h3e144a0_2
  - libdeflate=1.12=hac89ed1_0
  - libedit=3.1.20191231=h0678c8f_2
  - libev=4.33=haf1e3a3_1
  - libffi=3.4.2=h0d85af4_5
  - libgdal=3.5.0=h2acc0c7_4
  - libgfortran=5.0.0=9_3_0_h6c81a4c_23
  - libgfortran5=9.3.0=h6c81a4c_23
  - libglib=2.70.2=hf1fb8c0_4
  - libiconv=1.16=haf1e3a3_0
  - libkml=1.3.0=h8fd9edb_1014
  - liblapack=3.9.0=15_osx64_openblas
  - libnetcdf=4.8.1=nompi_h6609ca0_102
  - libnghttp2=1.47.0=h942079c_0
  - libopenblas=0.3.20=openmp_hb3cd9ec_0
  - libpng=1.6.37=h7cec526_2
  - libpq=14.4=hf6bb32a_0
  - librttopo=1.1.0=h52bd064_10
  - libsodium=1.0.18=hbcb3906_1
  - libspatialindex=1.9.3=he49afe7_4
  - libspatialite=5.0.1=ha6ecd9f_17
  - libssh2=1.10.0=h52ee1ee_2
  - libtiff=4.4.0=h9847915_1
  - libwebp=1.2.2=h28dabe5_0
  - libwebp-base=1.2.2=h0d85af4_1
  - libxcb=1.13=h0d85af4_1004
  - libxml2=2.9.14=h08a9926_0
  - libzip=1.8.0=h8b0c345_1
  - libzlib=1.2.12=hfe4f2af_1
  - llvm-openmp=14.0.4=ha654fa7_0
  - lz4-c=1.9.3=he49afe7_1
  - mapclassify=2.4.3=pyhd8ed1ab_0
  - markupsafe=2.1.1=py310h1961e1f_1
  - matplotlib=3.5.2=py310h2ec42d9_0
  - matplotlib-base=3.5.2=py310h4510841_0
  - matplotlib-inline=0.1.3=pyhd8ed1ab_0
  - mistune=0.8.4=py310he24745e_1005
  - munch=2.5.0=py_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - nb_conda=2.2.1=unix_6
  - nb_conda_kernels=2.3.1=py310h2ec42d9_1
  - nbclient=0.6.4=pyhd8ed1ab_1
  - nbconvert=6.5.0=pyhd8ed1ab_0
  - nbconvert-core=6.5.0=pyhd8ed1ab_0
  - nbconvert-pandoc=6.5.0=pyhd8ed1ab_0
  - nbformat=5.4.0=pyhd8ed1ab_0
  - ncurses=6.3=h96cf925_1
  - nest-asyncio=1.5.5=pyhd8ed1ab_0
  - networkx=2.8.4=pyhd8ed1ab_0
  - nitro=2.7.dev6=h96cf925_5
  - notebook=6.4.12=pyha770c72_0
  - nspr=4.32=hcd9eead_1
  - nss=3.78=ha8197d3_0
  - numpy=1.23.0=py310ha3f357c_0
  - openjpeg=2.4.0=h6e7aa92_1
  - openssl=1.1.1p=hfe4f2af_0
  - packaging=21.3=pyhd8ed1ab_0
  - pandas=1.4.3=py310h3099161_0
  - pandoc=2.18=h694c41f_0
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - parso=0.8.3=pyhd8ed1ab_0
  - pcre=8.45=he49afe7_0
  - pdal=2.4.2=h2e47583_1
  - pexpect=4.8.0=pyh9f0ad1d_2
  - pickleshare=0.7.5=py_1003
  - pillow=9.1.1=py310hb3240ae_1
  - pip=22.1.2=pyhd8ed1ab_0
  - pixman=0.40.0=hbcb3906_0
  - poppler=22.04.0=hed6754a_1
  - poppler-data=0.4.11=hd8ed1ab_0
  - postgresql=14.4=h600828a_0
  - proj=9.0.1=h05f0992_0
  - prometheus_client=0.14.1=pyhd8ed1ab_0
  - prompt-toolkit=3.0.30=pyha770c72_0
  - psutil=5.9.1=py310h6c45266_0
  - pthread-stubs=0.4=hc929b4f_1001
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pycparser=2.21=pyhd8ed1ab_0
  - pygments=2.12.0=pyhd8ed1ab_0
  - pyopenssl=22.0.0=pyhd8ed1ab_0
  - pyparsing=3.0.9=pyhd8ed1ab_0
  - pyproj=3.3.1=py310hac86e01_1
  - pyrsistent=0.18.1=py310h1961e1f_1
  - pysocks=1.7.1=py310h2ec42d9_5
  - python=3.10.5=hdaaf3db_0_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-fastjsonschema=2.15.3=pyhd8ed1ab_0
  - python-pdal=3.1.2=py310h5d8c707_2
  - python_abi=3.10=2_cp310
  - pytz=2022.1=pyhd8ed1ab_0
  - pyzmq=23.2.0=py310h85fb675_0
  - readline=8.1.2=h3899abd_0
  - requests=2.28.0=pyhd8ed1ab_1
  - rtree=1.0.0=py310had9ce37_1
  - scikit-learn=1.1.1=py310hfc06b38_0
  - scipy=1.8.1=py310h1f9c157_0
  - send2trash=1.8.0=pyhd8ed1ab_0
  - setuptools=62.6.0=py310h2ec42d9_0
  - shapely=1.8.2=py310h852e61b_2
  - six=1.16.0=pyh6c4a22f_0
  - snappy=1.1.9=h6e38e02_1
  - soupsieve=2.3.1=pyhd8ed1ab_0
  - sqlite=3.39.0=hd9f0692_0
  - stack_data=0.3.0=pyhd8ed1ab_0
  - terminado=0.15.0=py310h2ec42d9_0
  - threadpoolctl=3.1.0=pyh8a188c0_0
  - tiledb=2.9.5=hb1ce2c0_0
  - tinycss2=1.1.1=pyhd8ed1ab_0
  - tk=8.6.12=h5dbffcc_0
  - tornado=6.1=py310h1961e1f_3
  - traitlets=5.3.0=pyhd8ed1ab_0
  - traittypes=0.2.1=pyh9f0ad1d_2
  - tzcode=2022a=h5eb16cf_0
  - tzdata=2022a=h191b570_0
  - unicodedata2=14.0.0=py310h1961e1f_1
  - urllib3=1.26.9=pyhd8ed1ab_0
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - webencodings=0.5.1=py_1
  - wheel=0.37.1=pyhd8ed1ab_0
  - widgetsnbextension=3.6.1=pyha770c72_0
  - xerces-c=3.2.3=hf5b2a72_5
  - xorg-libxau=1.0.9=h35c211d_0
  - xorg-libxdmcp=1.1.3=h35c211d_0
  - xyzservices=2022.6.0=pyhd8ed1ab_0
  - xz=5.2.5=haf1e3a3_1
  - zeromq=4.3.4=he49afe7_1
  - zipp=3.8.0=pyhd8ed1ab_0
  - zlib=1.2.12=hfe4f2af_1
  - zstd=1.5.2=ha9df2e0_1
  - pip:
    - gdal==3.5.0
    - pdal-plugins==1.2.0
prefix: /Users/cole/anaconda3/envs/3dep
